// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Datas.Tables
{
#nullable enable
    [Serializable]
    public partial class FieldTransform
    {
        public string Name = string.Empty;
        public int Size;
        public int Slot;
        public int CostTicks;
        public List<Pair<string, int>> CostResources = new();
        public List<string> Requires = new();
    }

#nullable restore
}

