// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Datas.Tables
{
#nullable enable
    [Serializable]
    public partial class Field
    {
        public string Name = string.Empty;
        public bool Empty;
    }

#nullable restore
}

