// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Datas.Tables
{
#nullable enable
    [Serializable]
    public partial class Job
    {
        public string Name = string.Empty;
        public List<Pair<string, int>> CostResources = new();
    }

#nullable restore
}

