// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoWorld.Core.Data
{
#nullable enable
    [Serializable]
    public partial class GridMap
    {
        public int Size;
        public int X;
        public int Y;
    }

#nullable restore
}

