// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AutoWorld.Core.Data
{
#nullable enable
    [Serializable]
    public partial class Task
    {
        public string Field = string.Empty;
        public string Name = string.Empty;
        public string JobName = string.Empty;
        public int Tick;
        public string Result = string.Empty;
    }

#nullable restore
}

