// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Datas.Const
{
#nullable enable
    [Serializable]
    public partial class InitConst
    {
        public int WorkerTicks;
        public int DestroyTicks;
        public int FoodConsumeTicks;
        public int SoldierUpgradeTicks;
        public List<string> InitJobs = new();
        public int InitBadLandSize;
        public List<string> InitFields = new();
        public int InitFood;
        public int MillisecondPerTick;
        public int MaxSoldierLevel;
    }

#nullable restore
}

