@startuml
  package "Core" {
    class CoreRuntime
    class GameSession
    class ManualTickScheduler
    class EventManager
    class EventRegistryService
    class CitizenManager
    class FieldManager
    class ResourceManager
    interface ITickScheduler
    interface ITickListener
    interface IEventManager
    interface IGameSession
    interface IEventListener
  }

  package "Loading" {
    class DataLoadingController
    class DataLoadingPipeline
    interface ILoadStep
    class DomainBootstrapStep
    class LoadingContext
  }

  package "Game" {
    class GameLoopController
    class GameUIController
    class GridVisualizer
  }

  DataLoadingController --> DataLoadingPipeline : 파이프라인준비
  DataLoadingPipeline o-- ILoadStep : 스텝목록
  DataLoadingPipeline --> LoadingContext : 실행
  DomainBootstrapStep ..|> ILoadStep

  DomainBootstrapStep --> LoadingContext : 세션등록
  DomainBootstrapStep -u-> CoreRuntime : 세션생성요청

  CoreRuntime *-- GameSession : 보관
  CoreRuntime --> ManualTickScheduler : 스케줄러생성
  CoreRuntime --> CitizenManager : 초기화
  CoreRuntime --> FieldManager : 초기화
  CoreRuntime --> ResourceManager : 초기화
  CoreRuntime --> EventRegistryService : 초기화

  GameSession --|> IGameSession
  GameSession o-- ManualTickScheduler : 스케줄러
  GameSession o-- CitizenManager
  GameSession o-- FieldManager
  GameSession o-- ResourceManager
  GameSession o-- EventRegistryService
  GameSession --> EventManager : 디버그로그설정

  ManualTickScheduler ..|> ITickScheduler
  ManualTickScheduler --> ITickListener : 등록

  CitizenManager ..|> ITickListener
  CitizenManager ..|> IEventListener
  CitizenManager --> EventRegistryService : 식별자발급

  FieldManager ..|> ITickListener
  FieldManager ..|> IEventListener
  FieldManager --> EventRegistryService : 식별자발급

  ResourceManager ..|> ITickListener
  ResourceManager ..|> IEventListener
  ResourceManager --> EventRegistryService : 식별자발급

  EventManager --|> IEventManager
  EventManager --> IEventListener : 이벤트알림

  GameLoopController --> CoreRuntime : 세션조회
  GameLoopController --> IGameSession : 틱진행
  GameLoopController --> GridVisualizer : 필드표시

  GameUIController ..|> IEventListener
  GameUIController --> IEventManager : 이벤트구독
  GameUIController --> CoreRuntime : 세션획득
  GameUIController --> IGameSession : 상태조회
@enduml
